This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file /Users/enniomeier/Documents/Studium/FS18/Bachelorarbeit/Dokumentation/TechnischerBericht/.texpadtmp/Archbot-Technischer_Bericht_print_ba.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/enniomeier/Documents/Studium/FS18/Bachelorarbeit/Dokumentation/TechnischerBericht/.texpadtmp/Archbot-Technischer_Bericht_print_ba.acn...done (0 entries accepted, 0 rejected).
Nothing written in /Users/enniomeier/Documents/Studium/FS18/Bachelorarbeit/Dokumentation/TechnischerBericht/.texpadtmp/Archbot-Technischer_Bericht_print_ba.acr.
Transcript written in /Users/enniomeier/Documents/Studium/FS18/Bachelorarbeit/Dokumentation/TechnischerBericht/.texpadtmp/Archbot-Technischer_Bericht_print_ba.alg.
